import { AgentDefinition } from "./types";

const defaultTools: AgentDefinition["defaultTools"] = ["Read", "Bash", "Grep"];

export const agentSeedData: AgentDefinition[] = [
  // most-used
  {
    id: "annual-review",
    name: "Annual Review",
    summary: "Automates preparation of yearly client risk and performance reviews.",
    description: "Automates preparation of yearly client risk and performance reviews.",
    icon: "calendar-check",
    category: "operations",
    displayCategory: "most-used",
    defaultModel: "sonnet",
    defaultTools,
    systemPrompt: "",
    agentFileContent: "",
  },
  {
    id: "credit-memo-production",
    name: "Credit Memo Production",
    summary: "Auto-generates structured Credit Memos from data inputs.",
    description: "Auto-generates structured Credit Memos from data inputs.",
    icon: "file-text",
    category: "operations",
    displayCategory: "most-used",
    defaultModel: "sonnet",
    defaultTools,
    systemPrompt: "",
    agentFileContent: "",
  },

  // acquisition
  {
    id: "customer-profile",
    name: "Customer Profile",
    summary: "Automates curation of demographic, financial, and behavioural data to build a customer profile.",
    description: "Automates curation of demographic, financial, and behavioural data to build a customer profile.",
    icon: "user-circle",
    category: "operations",
    displayCategory: "acquisition",
    defaultModel: "sonnet",
    defaultTools,
    systemPrompt: "",
    agentFileContent: "",
  },
  {
    id: "industry-research",
    name: "Industry Research",
    summary: "Summarizes sector trends, benchmarks, and regulatory insights, competitive landscape.",
    description: "Summarizes sector trends, benchmarks, and regulatory insights, competitive landscape.",
    icon: "search",
    category: "operations",
    displayCategory: "acquisition",
    defaultModel: "sonnet",
    defaultTools,
    systemPrompt: "",
    agentFileContent: "",
  },
  {
    id: "meeting-prep-production",
    name: "Meeting Prep Production",
    summary: "Prepares personalised, data-rich briefings before client meetings.",
    description: "Prepares personalised, data-rich briefings before client meetings.",
    icon: "briefcase",
    category: "operations",
    displayCategory: "acquisition",
    defaultModel: "sonnet",
    defaultTools,
    systemPrompt: "",
    agentFileContent: "",
  },
  {
    id: "market-pricing-movements",
    name: "Market Pricing Movements",
    summary: "TBD",
    description: "TBD",
    icon: "trending-up",
    category: "operations",
    displayCategory: "acquisition",
    defaultModel: "sonnet",
    defaultTools,
    systemPrompt: "",
    agentFileContent: "",
  },
  {
    id: "dynamic-market-pricing",
    name: "Dynamic Market Pricing",
    summary: "Aggregates live market, competitor, and rate data to suggest optimal pricing.",
    description: "Aggregates live market, competitor, and rate data to suggest optimal pricing.",
    icon: "dollar-sign",
    category: "operations",
    displayCategory: "acquisition",
    defaultModel: "sonnet",
    defaultTools,
    systemPrompt: "",
    agentFileContent: "",
  },
  {
    id: "prospect-sourcing",
    name: "Prospect Sourcing",
    summary: "Identifies potential clients to up-sell opportunities based on segments and risk appetite.",
    description: "Identifies potential clients to up-sell opportunities based on segments and risk appetite.",
    icon: "users",
    category: "operations",
    displayCategory: "acquisition",
    defaultModel: "sonnet",
    defaultTools,
    systemPrompt: "",
    agentFileContent: "",
  },

  // screening
  {
    id: "ubo-structuring",
    name: "UBO Structuring",
    summary: "Maps ultimate beneficial ownership structures with entity linkages.",
    description: "Maps ultimate beneficial ownership structures with entity linkages.",
    icon: "network",
    category: "operations",
    displayCategory: "screening",
    defaultModel: "sonnet",
    defaultTools,
    systemPrompt: "",
    agentFileContent: "",
  },
  {
    id: "sighting-papers",
    name: "Sighting Papers",
    summary: "Distressed down Credit Memo in order to gauge early feedback from credit & relationship teams.",
    description: "Distressed down Credit Memo in order to gauge early feedback from credit & relationship teams.",
    icon: "file-check",
    category: "operations",
    displayCategory: "screening",
    defaultModel: "sonnet",
    defaultTools,
    systemPrompt: "",
    agentFileContent: "",
  },
  {
    id: "heads-of-terms",
    name: "Heads of Terms",
    summary: "Drafts preliminary deal terms based on negotiation inputs and policy constraints.",
    description: "Drafts preliminary deal terms based on negotiation inputs and policy constraints.",
    icon: "scale",
    category: "operations",
    displayCategory: "screening",
    defaultModel: "sonnet",
    defaultTools,
    systemPrompt: "",
    agentFileContent: "",
  },
  {
    id: "policy-mapping",
    name: "Policy Mapping",
    summary: "Retrieves and interprets internal policy docs in natural language.",
    description: "Retrieves and interprets internal policy docs in natural language.",
    icon: "book-open",
    category: "operations",
    displayCategory: "screening",
    defaultModel: "sonnet",
    defaultTools,
    systemPrompt: "",
    agentFileContent: "",
  },
  {
    id: "adverse-media",
    name: "Adverse Media",
    summary: "Ongoing screening of entities across news and risk feeds with risk/sourcing and policy applied.",
    description: "Ongoing screening of entities across news and risk feeds with risk/sourcing and policy applied.",
    icon: "alert-triangle",
    category: "operations",
    displayCategory: "screening",
    defaultModel: "sonnet",
    defaultTools,
    systemPrompt: "",
    agentFileContent: "",
  },
  {
    id: "sic-code-validation",
    name: "SIC Code Validation",
    summary: "Validates and assigns accurate industry codes with an analysis business activities/risk profiles.",
    description: "Validates and assigns accurate industry codes with an analysis business activities/risk profiles.",
    icon: "hash",
    category: "operations",
    displayCategory: "screening",
    defaultModel: "sonnet",
    defaultTools,
    systemPrompt: "",
    agentFileContent: "",
  },
  {
    id: "cra-scorecard",
    name: "CRA Scorecard",
    summary: "Automates creation and calculation of AML risk.",
    description: "Automates creation and calculation of AML risk.",
    icon: "shield",
    category: "operations",
    displayCategory: "screening",
    defaultModel: "sonnet",
    defaultTools,
    systemPrompt: "",
    agentFileContent: "",
  },
  {
    id: "kyb-kyc-screening",
    name: "KYB/KYC Screening",
    summary: "Automates business and individual verification against regulatory and sanctions databases.",
    description: "Automates business and individual verification against regulatory and sanctions databases.",
    icon: "shield-check",
    category: "operations",
    displayCategory: "screening",
    defaultModel: "sonnet",
    defaultTools,
    systemPrompt: "",
    agentFileContent: "",
  },

  // underwriting
  {
    id: "business-financial-analysis",
    name: "Business Financial Analysis",
    summary: "Interprets company financials to assess performance and trends.",
    description: "Interprets company financials to assess performance and trends.",
    icon: "bar-chart",
    category: "operations",
    displayCategory: "underwriting",
    defaultModel: "sonnet",
    defaultTools,
    systemPrompt: "",
    agentFileContent: "",
  },
  {
    id: "consumer-financial-analysis",
    name: "Consumer Financial Analysis",
    summary: "Analyses personal income, expenses, and liabilities.",
    description: "Analyses personal income, expenses, and liabilities.",
    icon: "piggy-bank",
    category: "operations",
    displayCategory: "underwriting",
    defaultModel: "sonnet",
    defaultTools,
    systemPrompt: "",
    agentFileContent: "",
  },
  {
    id: "bank-statement-analysis",
    name: "Bank Statement Analysis",
    summary: "Extracts and categorises transactions with anomaly detection.",
    description: "Extracts and categorises transactions with anomaly detection.",
    icon: "credit-card",
    category: "operations",
    displayCategory: "underwriting",
    defaultModel: "sonnet",
    defaultTools,
    systemPrompt: "",
    agentFileContent: "",
  },
  {
    id: "business-cashflow-forecasting",
    name: "Business Cashflow Forecasting",
    summary: "Combines P&L, balance sheet, and repayment data to stress-test serviceability.",
    description: "Combines P&L, balance sheet, and repayment data to stress-test serviceability.",
    icon: "line-chart",
    category: "operations",
    displayCategory: "underwriting",
    defaultModel: "sonnet",
    defaultTools,
    systemPrompt: "",
    agentFileContent: "",
  },
  {
    id: "consumer-affordability-analysis",
    name: "Consumer Affordability Analysis",
    summary: "Automates budget breakdowns and affordability scoring aligned with bank policy assumptions.",
    description: "Automates budget breakdowns and affordability scoring aligned with bank policy assumptions.",
    icon: "calculator",
    category: "operations",
    displayCategory: "underwriting",
    defaultModel: "sonnet",
    defaultTools,
    systemPrompt: "",
    agentFileContent: "",
  },
  {
    id: "consumer-property-analysis",
    name: "Consumer Property Analysis",
    summary: "Aggregates market data, comparables, and local metrics.",
    description: "Aggregates market data, comparables, and local metrics.",
    icon: "home",
    category: "operations",
    displayCategory: "underwriting",
    defaultModel: "sonnet",
    defaultTools,
    systemPrompt: "",
    agentFileContent: "",
  },
  {
    id: "esg-analysis",
    name: "ESG Analysis",
    summary: "Assesses clients against environmental, social, and governance factors.",
    description: "Assesses clients against environmental, social, and governance factors.",
    icon: "leaf",
    category: "operations",
    displayCategory: "underwriting",
    defaultModel: "sonnet",
    defaultTools,
    systemPrompt: "",
    agentFileContent: "",
  },
  {
    id: "underwriting-qc",
    name: "Underwriting QC",
    summary: "Tracks policy adherence and flags breaches or waivers.",
    description: "Tracks policy adherence and flags breaches or waivers.",
    icon: "clipboard-check",
    category: "operations",
    displayCategory: "underwriting",
    defaultModel: "sonnet",
    defaultTools,
    systemPrompt: "",
    agentFileContent: "",
  },

  // fulfillment
  {
    id: "valuation-analysis",
    name: "Valuation Analysis",
    summary: "Reviews valuation reports and ensures in line with bank and policy expectations.",
    description: "Reviews valuation reports and ensures in line with bank and policy expectations.",
    icon: "building-2",
    category: "operations",
    displayCategory: "fulfillment",
    defaultModel: "sonnet",
    defaultTools,
    systemPrompt: "",
    agentFileContent: "",
  },
  {
    id: "valuation-orchestration",
    name: "Valuation Orchestration",
    summary: "Coordinates multiple valuation methods including automated models.",
    description: "Coordinates multiple valuation methods including automated models.",
    icon: "workflow",
    category: "operations",
    displayCategory: "fulfillment",
    defaultModel: "sonnet",
    defaultTools,
    systemPrompt: "",
    agentFileContent: "",
  },
  {
    id: "safe-to-transact-verification",
    name: "Safe to Transact Verification",
    summary: "Confirms all compliance, credit, and documentation criteria met before drawdown.",
    description: "Confirms all compliance, credit, and documentation criteria met before drawdown.",
    icon: "check-circle",
    category: "operations",
    displayCategory: "fulfillment",
    defaultModel: "sonnet",
    defaultTools,
    systemPrompt: "",
    agentFileContent: "",
  },
  {
    id: "sba-post-close",
    name: "SBA Post Close",
    summary: "Automates post-close loan documentation and reporting.",
    description: "Automates post-close loan documentation and reporting.",
    icon: "archive",
    category: "operations",
    displayCategory: "fulfillment",
    defaultModel: "sonnet",
    defaultTools,
    systemPrompt: "",
    agentFileContent: "",
  },
  {
    id: "appraisal-review",
    name: "Appraisal Review",
    summary: "Validates third-party appraisals for consistency and accuracy.",
    description: "Validates third-party appraisals for consistency and accuracy.",
    icon: "file-search",
    category: "operations",
    displayCategory: "fulfillment",
    defaultModel: "sonnet",
    defaultTools,
    systemPrompt: "",
    agentFileContent: "",
  },

  // monitoring
  {
    id: "account-plans-productions",
    name: "Account Plans Productions",
    summary: "Synthesises customer data into annual relationship plans.",
    description: "Synthesises customer data into annual relationship plans.",
    icon: "notebook-pen",
    category: "operations",
    displayCategory: "monitoring",
    defaultModel: "sonnet",
    defaultTools,
    systemPrompt: "",
    agentFileContent: "",
  },
  {
    id: "early-warning-identification",
    name: "Early Warning Identification",
    summary: "Monitors leading indicators of credit deterioration.",
    description: "Monitors leading indicators of credit deterioration.",
    icon: "bell",
    category: "operations",
    displayCategory: "monitoring",
    defaultModel: "sonnet",
    defaultTools,
    systemPrompt: "",
    agentFileContent: "",
  },
  {
    id: "covenant-testing",
    name: "Covenant Testing",
    summary: "Automates covenant compliance tracking and breach alerts.",
    description: "Automates covenant compliance tracking and breach alerts.",
    icon: "test-tube",
    category: "operations",
    displayCategory: "monitoring",
    defaultModel: "sonnet",
    defaultTools,
    systemPrompt: "",
    agentFileContent: "",
  },
  {
    id: "ongoing-due-diligence",
    name: "Ongoing Due Diligence",
    summary: "Keeps KYC and financial diligence live with data refreshes from companies house, SPC, etc.",
    description: "Keeps KYC and financial diligence live with data refreshes from companies house, SPC, etc.",
    icon: "refresh-cw",
    category: "operations",
    displayCategory: "monitoring",
    defaultModel: "sonnet",
    defaultTools,
    systemPrompt: "",
    agentFileContent: "",
  },
  {
    id: "ongoing-financials-streaming",
    name: "Ongoing Financials Streaming",
    summary: "Streams live financial data feeds into risk systems.",
    description: "Streams live financial data feeds into risk systems.",
    icon: "line-chart",
    category: "operations",
    displayCategory: "monitoring",
    defaultModel: "sonnet",
    defaultTools,
    systemPrompt: "",
    agentFileContent: "",
  },
  {
    id: "excess-management",
    name: "Excess Management",
    summary: "Detects and manages borrowing or limit breaches.",
    description: "Detects and manages borrowing or limit breaches.",
    icon: "banknote",
    category: "operations",
    displayCategory: "monitoring",
    defaultModel: "sonnet",
    defaultTools,
    systemPrompt: "",
    agentFileContent: "",
  },
  {
    id: "ongoing-property-analysis",
    name: "Ongoing Property Analysis",
    summary: "Maintains live updates on collateral valuations.",
    description: "Maintains live updates on collateral valuations.",
    icon: "building",
    category: "operations",
    displayCategory: "monitoring",
    defaultModel: "sonnet",
    defaultTools,
    systemPrompt: "",
    agentFileContent: "",
  },
  {
    id: "distressed-lending-management",
    name: "Distressed Lending Management",
    summary: "Manages watch-list accounts with structured workflows.",
    description: "Manages watch-list accounts with structured workflows.",
    icon: "flame",
    category: "operations",
    displayCategory: "monitoring",
    defaultModel: "sonnet",
    defaultTools,
    systemPrompt: "",
    agentFileContent: "",
  },
  {
    id: "annual-review-monitoring",
    name: "Annual Review (Monitoring)",
    summary: "Automates preparation of yearly client risk and performance reviews.",
    description: "Automates preparation of yearly client risk and performance reviews.",
    icon: "calendar-check",
    category: "operations",
    displayCategory: "monitoring",
    defaultModel: "sonnet",
    defaultTools,
    systemPrompt: "",
    agentFileContent: "",
  },
];
