import {
  LucideIcon,
  CalendarCheck,
  FileText,
  UserCircle,
  Search,
  Briefcase,
  TrendingUp,
  DollarSign,
  Users,
  Network,
  FileCheck,
  Scale,
  BookOpen,
  AlertTriangle,
  Hash,
  Shield,
  ShieldCheck,
  BarChart3,
  PiggyBank,
  CreditCard,
  LineChart,
  Calculator,
  Home,
  Leaf,
  ClipboardCheck,
  Building2,
  Workflow,
  CheckCircle2,
  Archive,
  FileSearch,
  NotebookPen,
  Bell as BellIcon,
  TestTube2,
  RefreshCw,
  Banknote,
  AlertOctagon,
  Building,
  Flame,
  Bot,
} from "lucide-react";

const ICON_MAP: Record<string, LucideIcon> = {
  "calendar-check": CalendarCheck,
  "file-text": FileText,
  "user-circle": UserCircle,
  search: Search,
  briefcase: Briefcase,
  "trending-up": TrendingUp,
  "dollar-sign": DollarSign,
  users: Users,
  network: Network,
  "file-check": FileCheck,
  scale: Scale,
  "book-open": BookOpen,
  "alert-triangle": AlertTriangle,
  hash: Hash,
  shield: Shield,
  "shield-check": ShieldCheck,
  "bar-chart": BarChart3,
  "piggy-bank": PiggyBank,
  "credit-card": CreditCard,
  "line-chart": LineChart,
  calculator: Calculator,
  home: Home,
  leaf: Leaf,
  "clipboard-check": ClipboardCheck,
  "building-2": Building2,
  workflow: Workflow,
  "check-circle": CheckCircle2,
  archive: Archive,
  "file-search": FileSearch,
  "notebook-pen": NotebookPen,
  bell: BellIcon,
  "test-tube": TestTube2,
  "refresh-cw": RefreshCw,
  banknote: Banknote,
  "alert-octagon": AlertOctagon,
  building: Building,
  flame: Flame,
  bot: Bot,
};

export function getAgentIcon(iconName: string): LucideIcon {
  return ICON_MAP[iconName] ?? Bot;
}
